include(CheckCXXCompilerFlag)

macro(enable_CXX11)
  if(CMAKE_COMPILER_IS_GNUCXX OR (COMPILER_ID STREQUAL CLANG))
    check_cxx_compiler_flag(-std=c++11 HAS_CXX11)
    if(HAS_CXX11)
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
    else()
      check_cxx_compiler_flag(-std=c++0x HAS_CXX0x)
      if(HAS_CXX0x)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
      else()
        message(SEND_ERROR "Can't enable C++11 support")
      endif()
    endif()
  endif()
endmacro()
